// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWEAYq0jiwe89xgU4OFXuTfW4-YeKELig',
    appId: '1:223963417823:web:c6067b301a0bbf73b1ad6a',
    messagingSenderId: '223963417823',
    projectId: 'random-store-app-2026',
    authDomain: 'random-store-app-2026.firebaseapp.com',
    storageBucket: 'random-store-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl14hsh7eROpA_PoIUrqZii14lu0MlCGU',
    appId: '1:223963417823:android:bb86361da6d8c487b1ad6a',
    messagingSenderId: '223963417823',
    projectId: 'random-store-app-2026',
    storageBucket: 'random-store-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk7kXcDCq1fZEdnsMDr6_qIn09B_UxvUw',
    appId: '1:223963417823:ios:4b52335f33c4ad6db1ad6a',
    messagingSenderId: '223963417823',
    projectId: 'random-store-app-2026',
    storageBucket: 'random-store-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.randomStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk7kXcDCq1fZEdnsMDr6_qIn09B_UxvUw',
    appId: '1:223963417823:ios:4b52335f33c4ad6db1ad6a',
    messagingSenderId: '223963417823',
    projectId: 'random-store-app-2026',
    storageBucket: 'random-store-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.randomStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWEAYq0jiwe89xgU4OFXuTfW4-YeKELig',
    appId: '1:223963417823:web:fa92cb843c8c805ab1ad6a',
    messagingSenderId: '223963417823',
    projectId: 'random-store-app-2026',
    authDomain: 'random-store-app-2026.firebaseapp.com',
    storageBucket: 'random-store-app-2026.firebasestorage.app',
  );
}
